version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  next-build: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rcs_back_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs/gunicorn:/app/logs/gunicorn
      - ./rcs_back/media:/app/rcs_back/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    expose:
      - 8000
    restart: always


  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rcs_back_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: always

  nginx:
    build: ./compose/production/nginx
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - ./logs/nginx:/etc/nginx/logs
      - ./rcs_back/media:/app/rcs_back/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - next
      - flower
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  redis:
    image: redis:5.0
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
        - production_redis_data:/data
    restart: always

  celeryworker:
    <<: *django
    image: rcs_back_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: rcs_back_production_celerybeat
    command: /start-celerybeat
    volumes:
      - ./logs/celery:/app/logs/celery

  flower:
    <<: *django
    image: rcs_back_production_flower
    command: /start-flower
    expose:
      - 5555

  next:
    build: ../restarter
    command: yarn start
    volumes:
      - next-build:/home/next/build
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --post-hook 'chown user:777 /etc/letsencrypt && chown user:777 /var/www/certbot'; sleep 12h & wait $${!}; done;'"
