name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "1.26.2"
      - run: docker-compose -f local.yml up --build --detach
      - run: sleep 10
      - run: docker exec django bash -c "python manage.py test --settings config.settings.test --parallel --failfast"

  deploy-production:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy production with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/restarter
            git pull
            cd ~/rcs_back
            git pull
            docker-compose -f production.yml up --detach --build --force-recreate
