name: deploy front
on:
  workflow_dispatch:

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: deploy production with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/restarter
            git pull
            cd ~/rcs_back
            docker-compose -f production.yml up --detach --build --force-recreate
